version: 2.1

parameters:
  kre-image-tag:
    type: string
    default: "latest"
  agent-download-link:
    type: string
    default: ""
  job-info:
    type: string
    default: ""
  agent-config:
    type: string
    default: ""
  server-url:
    type: string
    default: ""
  TESTOPS_API_KEY:
    type: string
    default: ""
  TESTOPS_SERVER_URL:
    type: string
    default: ""
  TESTOPS_PROJECT_ID:
    type: string
    default: ""
  TESTOPS_SESSION_ID:
    type: string
    default: ""

jobs:
  katalon-test:
    docker:
      - image: katalonstudio/katalon:<< pipeline.parameters.kre-image-tag >>
    environment:
      AGENT_DOWNLOAD_LINK: << pipeline.parameters.agent-download-link >>
      JOB_INFO: << pipeline.parameters.job-info >>
      SERVER_URL: << pipeline.parameters.server-url >>
    steps:
      - run:
          name: Run Katalon Test
          command: |
            set -x
            set -o nounset

            echo "Checking Katalon network connection"
            curl -v -m 10 $SERVER_URL/info

            echo "Upgrading environments"
            echo "Upgrade Google Chrome"
            chrome_package='google-chrome-stable_current_amd64.deb'
            wget -O $chrome_package  https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            dpkg -i $chrome_package || apt -y -f install
            
            echo "Wrap Chrome binary"
            WRAPPER_PATH=$(readlink -f /usr/bin/google-chrome)
            BASE_PATH="$WRAPPER_PATH-base"
            mv "$WRAPPER_PATH" "$BASE_PATH"
            
            cat > "$WRAPPER_PATH" \<<_EOF
            #!/bin/bash
            # Note: exec -a below is a bashism.
            exec -a "\$0" "$BASE_PATH" --no-sandbox "\$@"
            _EOF
            chmod +x "$WRAPPER_PATH"
            
            echo "$(google-chrome --version)" >> $KATALON_VERSION_FILE || true

            echo "Installing Katalon agent"
            mkdir /agent && cd /agent
            wget -O agent "${AGENT_DOWNLOAD_LINK}"
            echo "${JOB_INFO}" >> job.json

            set +x
            echo "<< pipeline.parameters.agent-config >>" >> agentconfig
            set -x
            
            cat agentconfig
            chmod 777 *
            ls -al

            echo "Executing test"
            xvfb-run -s "-screen 0 $DISPLAY_CONFIGURATION" ./agent start-agent --ci
            ret_code=$?
            
            exit $ret_code

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - katalon-test
